# Generated by Django 5.0.1 on 2024-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('To DO', 'To DO'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=50)),
            ],
        ),
    ]
