# Generated by Django 5.0.1 on 2024-02-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To DO', 'To DO'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='To Do', max_length=50),
        ),
    ]
